### ISSUE TITLE
Creating new news posts

### ISSUE THREAD

**Issue by mikecroucher** [sods/sods.github.io#1]
I've created a couple of news posts by directly creating files in the _posts directory. Is this the correct way of doing things? The result appears to be OK but I'm wondering if there was some software I should have used instead.

**Comment by lawrennd** [comment]
That's correct as far as I know! We can add disqus commenting in. I have an
idea how to.

**Comment by lawrennd** [comment]
Posts look great.

It would be cool to do something on teaching programming with Marta too.

**Comment by mikecroucher** [comment]
Agreed - I'll email Marta and get something put together.
